### ISSUE TITLE
Xcode 26.4 build failure: use of private header 'netinet6/in6.h' in Leanplum module

### ISSUE THREAD

**Issue by michal-maciag** [Leanplum/Leanplum-iOS-SDK#601]
Hi Leanplum team!
## Problem
We’re encountering a build failure when integrating Leanplum with newer Xcode versions (works fine on Xcode 26.3, fails on newer versions).
The issue appears to be related to stricter module validation / dependency scanning in newer Xcode releases.
## Expected Behavior
Leanplum should compile successfully under newer Xcode versions.
## Actual Behavior
```
error: Clang dependency scanning failure: While building module 'Leanplum'

.../Leanplum_Reachability.h:33:9: error: use of private header from outside its module: 'netinet6/in6.h' [-Wprivate-header]

fatal error: could not build module 'Leanplum'
```

There's an additional message, while it's not fatal, I'm adding it here for completion's sake: 
```
warning: umbrella header for module 'Leanplum' does not include header 'Leanplum_WebSocket+Utils.h'
```
## Steps to reproduce the problem
1. Install Xcode 26.4
2. Add Leanplum SDK 6.6.1
3. Try to build the project
## Root Cause (suspected)
The issue seems to come from:
```
Leanplum_Reachability.h
#import <netinet6/in6.h>
```
netinet6/in6.h is treated as a private/non-modular header by newer Xcode versions, and importing it from a public framework header causes module build failure.
## Possible solution
Potential fix would be to simply remove the import from the header file (apparently most if not all of the needed signatures, are in the also imported public header: `#import <netinet/in.h>`)
## Specifications
* Version: 6.6.1
* Platform: iOS
* Subsystem: iOS 26+

**Comment by Jon889** [comment]
@nzagorchev Is there any update for this?
